- hosts: all
  become: yes
  tasks: 
   - name: Remove php5.6
     ansible.builtin.apt:
       name: php5.6
       autoremove: yes
   - name: Remove php5.6-fpm
     ansible.builtin.apt:
       name: php5.6-fpm
       autoremove: yes
   - name: install php7.2
     ansible.builtin.apt:
       name: php7.2
       state: present
   - name: install php7.2-fpm
     ansible.builtin.apt:
       name: php7.2-fpm
       state: present
   - name:  enable php7.2-conf #выводим статус в консоль для отладки
     ansible.builtin.shell:
       cmd: a2enconf php7.2-fpm
   - name:  disable php5.6-conf #выводим статус в консоль для отладки
     ansible.builtin.shell:
       cmd: a2disconf php5.6-fpm
   - name: status php #выводим статус в консоль для отладки
     ansible.builtin.shell:
       cmd: php -v
     register: cmd
   - debug: msg="{{ cmd }}"
   - name: restart apache
     ansible.builtin.service:
       name: apache2
       state: restarted




